# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pegawai.pegawai import *
from penggajian.penggajian import *

class Home(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(746, 561)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(140, 140, 461, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 80, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.pagePegawai)

        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 140, 181, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.pagePenggajian)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 40, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def pagePegawai(self):
        self.Form2 = QtWidgets.QDialog()
        self.ui = Pegawai()
        self.ui.setupUi(self.Form2)
        self.Form2.show()

    def pagePenggajian(self):
        self.Form3 = QtWidgets.QDialog()
        self.ui2 = Penggajian()
        self.ui2.setupUi(self.Form3)
        self.Form3.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Data Pegawai"))
        self.pushButton_3.setText(_translate("Form", "Hasil Gaji"))
        self.label.setText(_translate("Form", "PT. BEJO ABADI Tbk"))

class Manager:
    def __init__(self):
        self.first = Home()

        self.first.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Home()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
